---
services:
  localstack:
    image: localstack/localstack:4.3
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
    volumes:
      - "localstack-volume:/var/lib/localstack"
      - "./ready.d:/etc/localstack/init/ready.d/"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-volume:
